codingyun-blog/src/com/codingyun/core/entity/bo/BlogArticleBo.java
package com.codingyun.core.entity.bo;

import java.util.Date;

import com.codingyun.core.exception.ServiceException;
import com.codingyun.core.util.StringUtil;

/**
 * 博客文章
 * @author 王勇
 * 2014年8月13日
 */
public class BlogArticleBo {
	
	private int id;
	/**
	 * 文章标题
	 */
	private String title = "";
	/**
	 * 文章主体内容
	 */
	private String content = "";
	/**
	 * 文章内容的前面200字的节选,展示到列表上
	 */
	private String contentDesc = "";
	/**
	 * 发表时间
	 */
	private Date publishTime = new Date();
	/**
	 * 作者
	 */
	private String author = "coding云";
	/**
	 * 阅读次数
	 */
	private int userReadCount = 1;
	/**
	 * 分类
	 */
	private int category = 1;
	
	private Date createTime = new Date();
	
	/**
	 * 广告类型：1.alimama2.baidu3.谷歌  
	 */
	private int adCompanyType = 1;
	/**
	 * 广告内容类型：1.宽度640*90;2.宽度
	 */
	private int adBoxType = 1;
	/**
	 * 网页的关键词
	 */
	private String keyWords = "coding云,coding";
	/**
	 * 网页的描述
	 */
	private String description = "作为一个java程序员,coding云希望将自己懂得技术,包含但不限于nginx,tomcat,spring mvc,ssh等分享给大家。";

	/**
	 * 网页的tag
	 */
	private String tag = "";
	/**
	 * 是否展示：1展示，2不展示
	 */
	private int showFlag = 2;

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContentDesc() {
		return contentDesc;
	}

	public void setContentDesc(String contentDesc) {
		this.contentDesc = contentDesc;
	}

	public Date getPublishTime() {
		return publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public int getUserReadCount() {
		return userReadCount;
	}

	public void setUserReadCount(int userReadCount) {
		this.userReadCount = userReadCount;
	}

	public int getCategory() {
		return category;
	}

	public void setCategory(int category) {
		this.category = category;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	public int getShowFlag() {
		return showFlag;
	}

	public void setShowFlag(int showFlag) {
		this.showFlag = showFlag;
	}

	@Override
	public String toString() {
		return "BlogArticleBo [id=" + id + ", title=" + title + ", content="
				+ content + ", contentDesc=" + contentDesc + ", publishTime="
				+ publishTime + ", author=" + author + ", userReadCount="
				+ userReadCount + ", category=" + category + ", createTime="
				+ createTime + ", adCompanyType=" + adCompanyType
				+ ", adBoxType=" + adBoxType + ", keyWords=" + keyWords
				+ ", description=" + description + ", tag=" + tag
				+ ", showFlag=" + showFlag + "]";
	}
	
	public void saveVlidate() throws ServiceException{
		if(StringUtil.isEmpty(this.getTitle())){
			throw new ServiceException("title不可以为空");
		}
		if(StringUtil.isEmpty(this.getContent())){
			throw new ServiceException("内容不可以为空");
		}
	}
	
	

	public int getAdCompanyType() {
		return adCompanyType;
	}

	public void setAdCompanyType(int adCompanyType) {
		this.adCompanyType = adCompanyType;
	}

	public int getAdBoxType() {
		return adBoxType;
	}

	public void setAdBoxType(int adBoxType) {
		this.adBoxType = adBoxType;
	}

	public String getKeyWords() {
		return keyWords;
	}

	public void setKeyWords(String keyWords) {
		this.keyWords = keyWords;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getHtmlTitle(){
		return this.getTitle() + "_博客_coding云";
	}
	
	
	
}

codingyun-blog/src/com/codingyun/core/action/blog/ArticleController.java
package com.codingyun.core.action.blog;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.codingyun.core.action.BaseController;
import com.codingyun.core.entity.JsonResult;
import com.codingyun.core.entity.QueryCondition;
import com.codingyun.core.entity.bo.BlogArticleBo;
import com.codingyun.core.entity.vo.BlogArticleVo;
import com.codingyun.core.service.BlogArticleService;
import com.google.gson.Gson;

@Controller
@RequestMapping("/article")
public class ArticleController extends BaseController {
	
	private static Logger logger = Logger.getLogger(ArticleController.class);
	
	@Autowired
	private BlogArticleService blogArticleService;
	
	/**
	 * 根据网址获取文章的html页面
	 * 比如如下的URL：/123.html，则输出：
		namePart: 123, expandedPart: html. 
	 * @user 王勇
	 * 2014年8月14日
	 */
    @RequestMapping(value="/{namePart:[\\d]+}.{expandedPart:html}")  
    public String getArticleModel(HttpServletRequest request, @PathVariable int namePart, @PathVariable String expandedPart, QueryCondition queryCondition) throws Exception{  
    	logger.info("namePart: " + namePart + ", expandedPart: " + expandedPart);
    	BlogArticleVo article = blogArticleService.getArticleById(namePart);
    	if(article == null || article.getId() <= 0){
    		return "about/404"; 
    	}
    	request.setAttribute("article", article);
    	//获取相关文章
    	request.setAttribute("categoryArticleList", blogArticleService.getArticleList(article.getCategory(), queryCondition).getDatas());
    	//记得补充获取友情链接数据（放到缓存中）
        return "blog/article";  
    }  
    
    /**
     * 获取用户推荐的文章列表
     * @param queryCondition
     * @return
     */
    @RequestMapping(value = "getHotArticleList", method = RequestMethod.POST)
	@ResponseBody
    public String getHotArticleList(QueryCondition queryCondition){
    	List<BlogArticleVo> articleList = null;
    	JsonResult<BlogArticleBo> jsonResult = new JsonResult<BlogArticleBo>();
    	try {
    		articleList = blogArticleService.getArticleList(queryCondition).getDatas();
		} catch (Exception e) {
			e.printStackTrace();
		}
		if(articleList == null || articleList.size() <= 0){
			jsonResult.setResultCode(1);
			jsonResult.setResultMessage("获取用户推荐的文章列表失败");
		}
		jsonResult.setData(articleList);
		return new Gson().toJson(jsonResult);
    }
	
//	@RequestMapping(value = "getArticleById/{id}")
//	@ResponseBody
//	public Object getArticleById(HttpServletRequest request, @PathVariable String id){
//		try {
//			return blogArticleService.getArticleById(Integer.parseInt(id));
//		} catch (NumberFormatException e) {
//			e.printStackTrace();
//		} catch (Exception e) {
//			e.printStackTrace();
//		}
//		return null;
//	}

}

codingyun-blog/src/com/codingyun/core/action/blog/BlogIndexController.java
package com.codingyun.core.action.blog;
//package com.zkyj.core.action.blog;
//
//import javax.servlet.http.HttpServletRequest;
//
//import org.apache.log4j.Logger;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestMethod;
//
//import com.zkyj.core.action.BaseController;
//import com.zkyj.core.entity.PageBean;
//import com.zkyj.core.entity.QueryCondition;
//import com.zkyj.core.entity.bo.BlogArticleBo;
//import com.zkyj.core.service.BlogArticleService;
//
//@Controller
//@RequestMapping("/blog")
//public class BlogIndexController extends BaseController {
//	
//	private static Logger logger = Logger.getLogger(BlogIndexController.class);
//	
//	@Autowired
//	private BlogArticleService blogArticleService;
//	
//	/**
//	 * 博客主页
//	 * @user jack
//	 * 2014年8月6日
//	 */
//	@RequestMapping(value = "", method = RequestMethod.GET)
//	public String index(HttpServletRequest request , QueryCondition queryCondition){
//		PageBean<BlogArticleBo> articleBean = null;
//		try{
//			articleBean = blogArticleService.getArticleList(queryCondition);
//		}catch(Exception e){
//			e.printStackTrace();
//		}
//		request.setAttribute("articleList", articleBean != null ? articleBean.getDatas() : null);
//		request.setAttribute("pageInfo", articleBean);
//		logger.info("get article list size:" + articleBean.getDatas().size());
//		return "blog/blog";
//	}
//
//	/**
//	 * 留下你的想法（用户留言本）
//	 * @user jack
//	 * 2014年8月6日
//	 */
//	@RequestMapping(value = "leaveYourMind", method = RequestMethod.GET)
//	public String leaveYourMind(HttpServletRequest request , QueryCondition queryCondition){
//		return "blog/leaveYourMind";
//	}
//}

codingyun-blog/src/com/codingyun/core/action/blog/CategoryController.java
package com.codingyun.core.action.blog;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

import com.codingyun.core.entity.PageBean;
import com.codingyun.core.entity.QueryCondition;
import com.codingyun.core.entity.vo.BlogArticleVo;
import com.codingyun.core.service.BlogArticleService;

@Controller
@RequestMapping("/category")
public class CategoryController {
	
	private static Logger logger = Logger.getLogger(CategoryController.class);
	
	@Autowired
	private BlogArticleService blogArticleService;
	
	/**
	 * 根据分类获取文章列表
	 * @user 王勇
	 * 2015年6月11日
	 */
    @RequestMapping(value="/{categoryCode:[\\d]+}")  
    public String getArticleModel(HttpServletRequest request, @PathVariable int categoryCode, QueryCondition queryCondition) throws Exception{  
    	logger.info("categoryCode: " + categoryCode );
    	PageBean<BlogArticleVo> articleBean = null;
		try{
			articleBean = blogArticleService.getArticleList(categoryCode, queryCondition);
		}catch(Exception e){
			e.printStackTrace();
		}
		request.setAttribute("articleList", articleBean != null ? articleBean.getDatas() : null);
		request.setAttribute("pageInfo", articleBean);
		request.setAttribute("categoryCode", categoryCode);
		logger.info("get article list size:" + articleBean.getDatas().size());
        return "blog/blog";  
    } 

}

codingyun-blog/src/com/codingyun/core/action/blog/TagController.java
package com.codingyun.core.action.blog;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

import com.codingyun.core.entity.PageBean;
import com.codingyun.core.entity.QueryCondition;
import com.codingyun.core.entity.vo.BlogArticleVo;
import com.codingyun.core.service.BlogArticleService;
import com.codingyun.core.util.StringUtil;

@Controller
@RequestMapping("/tag")
public class TagController {
	
	private static Logger logger = Logger.getLogger(TagController.class);
	
	@Autowired
	private BlogArticleService blogArticleService;
	
	/**
	 * 根据分类获取文章列表
	 * @user 王勇
	 * 2015年6月11日
	 */
	 @RequestMapping(value="/{tag}")  
    public String getArticleListByTag(HttpServletRequest request, @PathVariable String tag, QueryCondition queryCondition) throws Exception{  
//    	tag = new String(tag.getBytes("ISO-8859-1"), "UTF-8");   
//		tomcat 下如果配置 server.xml配置了URIEncoding="UTF-8"，则无需执行上一步转码
//		 <Connector port="8080" protocol="HTTP/1.1"
//         connectionTimeout="20000"
//         redirectPort="8443" URIEncoding="UTF-8" />  
		 
    	logger.info("tag: " + tag );
    	PageBean<BlogArticleVo> articleBean = null;
		try{
			articleBean = blogArticleService.getTagArticleList(queryCondition, tag);
		}catch(Exception e){
			e.printStackTrace();
		}
		request.setAttribute("articleList", articleBean != null ? articleBean.getDatas() : null);
		request.setAttribute("pageInfo", articleBean);
		if(StringUtil.isNotBlank(tag)){
			request.setAttribute("tagCode", 1);
		}
		request.setAttribute("tagName", "阿里云");
		logger.info("get article list size:" + articleBean.getDatas().size());
        return "blog/blog";  
    } 

}

codingyun-blog/WebContent/WEB-INF/jsp/blog/article.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/common/taglibs.jsp"%>
<!DOCTYPE html>
<html lang="zh-cn" xmlns:wb="http://open.weibo.com/wb">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="${article.description }">
    <meta name="keywords" content="${article.keyWords }"/>
    <meta name="author" content="coding云">
    <!-- 微博的赞 -->
    <!--必填-->
	<meta property="og:type" content="article" />
	<meta property="og:url" content="www.codingyun.com/article/${article.id}.html" />
	<meta property="og:title" content="${article.htmlTitle}" />
	<meta property="og:description" content="${article.description }" />
	<!--选填-->
<!-- 	<meta property="og:image" content="文章的显示图片" /> -->
<!-- 	<meta name="weibo: article:create_at" content="文章的创建时间" /> -->
<!-- 	<meta name="weibo: article:update_at" content="文章的更新时间" /> -->
        
    <link rel="icon" href="../../favicon.ico">

    <title>${article.htmlTitle}</title>

    <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="${baseUrlStatic}/Font-Awesome-3.2.1/css/font-awesome.min.css" rel="stylesheet">
    <!-- 新浪微博评论箱 -->
	<script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js?appkey=17994897" type="text/javascript" charset="utf-8"></script>
    <!-- Custom styles for this template -->
    <link href="${baseUrlStatic}/css/blog/blog.css?version=${version}" rel="stylesheet">
<%--     <link href="${baseUrlStatic}/syntaxhighlighter_3.0.83/styles/shCore.css" rel="stylesheet" type="text/css"> --%>
	<link href="${baseUrlStatic}/syntaxhighlighter_3.0.83/styles/shCoreRDark.css?version=${version}" rel="stylesheet" type="text/css">
    <style type="text/css">
    	pre {
		    margin: 0;
    		padding: 0;
		}
		blockquote {
			font-size: 15px;
		}
    </style>
    
  </head>

  <body>
  
    <jsp:include page="common/topSideBar.jsp" />

    <div class="container">

      <jsp:include page="common/blogHeader.jsp" />
      
      <div class="row">
        <div class="col-sm-8 blog-main">
          <!-- 阿里云优惠券推广位 -->
       	  <div style="margin-bottom: 15px;">
<%--        		<c:if test="${article.adCompanyType == 1 && article.adBoxType == 1 }"> --%>
<!-- 	       		<a href="http://s.click.taobao.com/t?e=m%3D2%26s%3D1SP%2BYcrwvUUcQipKwQzePCperVdZeJviEViQ0P1Vf2kguMN8XjClAr5myjbCyDIJ66gI2QqyOEDPmk5F76YCnAFBPesJXGs2bk%2B8hdThBUSHrj9Leaj0X%2Bdn1BbglxZYxUhy8exlzcq9AmARIwX9K2Zg%2BdzdQFOwfMRvoxSVDSdLyrb2g0H2G5JcxXijM%2BwneEHpPTskRHlFYAAV9gnNuPTL%2BS6jTvPzN7YQp05KcLcunFBf1wJnpg%3D%3D" target="_blank"> -->
<!-- 	       			<img src="http://gtms02.alicdn.com/tps/i2/TB11cZ3FFXXXXbLXXXXSNBf1pXX-640-90.jpg" /> -->
<!-- 	       		</a> -->
<%--        		</c:if> --%>
<%--        		<c:if test="${article.adCompanyType == 1 && article.adBoxType == 2 }"> --%>
<!-- 	       		<a href="http://s.click.taobao.com/t?e=m%3D2%26s%3D%2FLxg%2FpQUGpIcQipKwQzePCperVdZeJviEViQ0P1Vf2kguMN8XjClAjN8WyfMApDeUICy6uSC4THPmk5F76YCnAFBPesJXGs2bk%2B8hdThBUQDSWCaAf%2FTqedn1BbglxZYxUhy8exlzcq9AmARIwX9K%2BnbtOD3UdznPV1H2z0iQv9NkKVMHClW0QbMqOpFMIvnvjQXzzpXdTHGJe8N%2FwNpGw%3D%3D" target="_blank"> -->
<!-- 	       			<img src="http://gtms02.alicdn.com/tps/i2/TB12KUWFFXXXXXwXpXXzAFS0VXX-640-90.jpeg" /> -->
<!-- 	       		</a> -->
<%--        		</c:if> --%>
       	  </div>

          <div class="blog-post">
          	 <div style="display:inline-block;vertical-align:top;margin-top: 2px;margin-right: 5px;">
          	 	<a href='/category/${article.category}' style="color: #4c4c4c;" >
					<div class="tooltip-inner" style="padding: 3px 15px;"> ${article.categoryName } </div>
				</a>
          	 </div>
          	 <div style="display:inline-block;vertical-align:top;">
          	 	<h3 class="blog-post-title" >
 		          	 ${article.title}
          	 	</h3>
          	 </div>
            <fmt:formatDate var="publishTime" value="${article.publishTime}" pattern="yyyy-MM-dd HH:mm" />
            <p class="blog-post-meta">
            	<i class="icon-calendar"></i> <span id="publishTime" style="margin-right:10px;">${publishTime}</span> |
            	<i class="icon-user"></i> <span id="author" style="margin-right:10px;">${article.author} </span> |
            	<i class="icon-book"></i> <span id="userReadCount" style="margin-right:10px;">${article.userReadCount}次阅读</span> |
            	<a href="#tagArticle"><i class="icon-comments"></i> <span class="ds-thread-count" data-thread-key="${article.id}"></span></a>
           	</p>
           	
           	<!-- 百度 ads -->
           	<script type="text/javascript">
			    /*728*15 创建于 2014-10-21*/
			    var cpro_id = "u1769646";
			</script>
			<script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
		    <!-- 百度 ads end-->
		    
            <div id="content" style="margin-top:20px;margin-bottom:20px;">
            	${article.content}
            </div>
            <div class="clickforWhole" style="font-size: 12px;border-bottom: 1px solid #ddd;padding-bottom:25px;padding-top:10px;">
             	<span class="glyphicon glyphicon-tag" aria-hidden="true"></span> 
             	<c:forEach var="tagName" items="${article.tagList }" varStatus="statusTag">
             		<a href='/tag/${tagName}'>${tagName }</a>
             		<c:if test="${statusTag.last == false}">
             			,
             		</c:if>
             	</c:forEach>
<%--           		<a class="pull-right" style="font-size:18px;" target="_blank" href='/article/${article.id}.html'>阅读全文...</a> --%>
           
	            <!-- 微博的赞 -->
	            <div style="float:right;">
	            	<wb:like appkey="1xxPX" type="number"></wb:like>
	            </div>
	            <!-- 微博的分享 -->
	            <div style="float:right;margin-right: 20px;">
	            	<wb:share-button appkey="1xxPX" addition="simple" type="button" ralateUid="5216152378" 
	           			default_text="作为一个java程序员，我希望将自己懂得技术，包含但不限于nginx，tomcat，spring mvc，ssh等分享给大家。纯java做的网站，有博客，有演示系统，感兴趣当然得关注喽"></wb:share-button>
	            </div>
            </div>
         
            
            
   		    <!-- baidu ads -->
      	    <script type="text/javascript">
			    /*760*90 文章下方 2014-10-22*/
			    var cpro_id = "u1770423";
		    </script>
		    <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
	        <!-- baidu ads end-->
          
            
          </div><!-- /.blog-post -->
          
          
          <!-- 相关文章 -->
          <div id="tagArticle">
		  	 	<div class="panel panel-primary">
				  <!-- Default panel contents -->
				  <div class="panel-heading">
				  	<h3 class="panel-title">相关文章</h3>
				  </div>
				  <!-- List group -->
				  <div class="list-group">
				  	  <c:forEach var="article" items="${categoryArticleList}" varStatus="status">
				  	  	<fmt:formatDate var="publishDate" value="${article.publishTime}" pattern="yyyy年MM月dd日" />
			  	  		<a href='/article/${article.id}.html' class="list-group-item ">
			  	  			<div class="col-md-3">
				  	  			<span style="margin-right:10px;">${publishDate}</span>
			  	  			</div>
			  	  			<div>
				  	  			${article.title}
			  	  			</div>
			  	  		</a>
				      </c:forEach>
				  </div>
				</div>
		  </div>
          <!-- /.相关文章 -->
          
          <div id="weiboComment">
          	<!-- 多说评论框 start -->
			<div class="ds-thread" data-thread-key="${article.id}" data-title="${article.title}" 
				data-url='www.codingyun.com/article/${article.id}.html'
				data-order="desc" data-limit="15"></div>
			<!-- 多说评论框 end -->
			<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
			<script type="text/javascript">
				var duoshuoQuery = {short_name:"codingyun"};
				(function() {
					var ds = document.createElement('script');
					ds.type = 'text/javascript';ds.async = true;
					ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
					ds.charset = 'UTF-8';
					(document.getElementsByTagName('head')[0] 
					 || document.getElementsByTagName('body')[0]).appendChild(ds);
				})();
			</script>
			<!-- 多说公共JS代码 end -->
          	
<!--      微博评论框（暂时不用）     	<wb:comments url="auto" width="auto" appkey="17994897" ralateuid="5216152378" ></wb:comments> -->
          </div>
        </div><!-- /.blog-main -->

  		<jsp:include page="common/rightSideBar.jsp" />
  		
      </div><!-- /.row -->

    </div><!-- /.container -->
    <!-- google ads -->
    <!-- google ads end-->

    <jsp:include page="common/footerSideBar.jsp" />
    
   	<!-- 百度ad -->
	<script src="http://cpro.baidustatic.com/cpro/ui/s.js" type="text/javascript"></script>
	<!-- 百度ad -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- 请首先引用jquery，再引用其他js文件 -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="${baseUrlStatic}/js/blog/article.js?ver=${version}"></script>
    <script src="${baseUrlStatic}/syntaxhighlighter_3.0.83/scripts/shCore.js" type="text/javascript"></script>
	<script src="${baseUrlStatic}/syntaxhighlighter_3.0.83/scripts/shBrushJava.js" type="text/javascript"></script>
	<script type="text/javascript">SyntaxHighlighter.all();</script>
    <script type="text/javascript">
	    $(document).ready(function(){
	    	$("#blog-masthead").find('a').removeClass('active');
	    	$("#blog-masthead .blog-nav .blog").addClass('active');
	    });
    </script>
  </body>
</html>